[package]
name = "vodbot"
version = "0.1.0"
authors = ["Logan Hickok-Dickson <self@notquiteapex.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
